### ISSUE TITLE
AWSSQS - Allow SqsMessageProducer to publish message to SNS based on Message Header

### ISSUE THREAD

**Issue by honkuan86** [BrighterCommand/Brighter#1554]
**Is your feature request related to a problem? Please describe.**
Currently SqsMessageProducer is publishing messages to a SNS topic based on RoutingKey. However a RoutingKey can only be specify once in Configuration, and limits the producer only can send to a single SNS topic.

**Describe the solution you'd like**
Allow SqsMessageProducer  to publish message to a SNS topic based on Message Header, so that a publisher can publish to different SNS topic.

**Comment by iancooper** [comment]
Hi @honkuan86. Let me take a look at this, and see if I can figure out what changed from other transports and why. And then I can figure out the fix.

**Comment by iancooper** [comment]
@honkuan86 Opened a PR. Done by tomorrow.

**Comment by iancooper** [comment]
@honkuan86 This should be fixed. We now have an internal mapping of topics to topic Arns. On a 'on demand' creation, or validate by name basis, we will build this mapping as we encounter topics in headers, so that we only need to do the expensive AWS lookup once, and replace it with an O(1) dictionary lookup. If you want us to validate by Arn, primarily because you have externally created Arns, and you don't want us to create, you now need to pass the mapping of topics to topicArns in on the publication, over us creating it. So for any topic in a message with that strategy we can use your dictionary to look up the Arn

Hope that makes sense
