### ISSUE TITLE
Command Processor Keeps track of Outstanding Message count (In Outbox) when it is a Scoped Service

### ISSUE THREAD

**Issue by preardon** [BrighterCommand/Brighter#1619]
When Clear Messages is called on the Command Processor, it runs a CheckOutstandingMessages in a background task as this is expensive, however when we are running the Command Processor as a Scoped Service it is updating a variable that is about to be disposed.

Another thing to note here, is that at the beginning of ClearOutbox it runs a CheckOutboxOutstandingLimit, the first time this is run in a Scoped Pipeline I would expect it to be 0 meaning that we could run into a situation in a scoped Command Processor that the First Clear/Post inside the Scope it works and fails all subsequent times (Obviously Running the Sweeper will help with this, just a note)

@iancooper  How would you feel about this Check not being performed inside of Scoped Command Processors

**Comment by iancooper** [comment]
It's an interesting one as scoped command processors can be a little bit of a pain around some assumptions we have. We also use background processes for publisher confirms from RMQ or producer callbacks from Kafka, because they will occur asynchronously, and if we don't have a command processor around any more, there is no way to update the dispatched list.

The Command Processor really works best as a singleton, and not as a transient dependency. I wonder if we need to think again about a scoped command processor being the solution to our needs...

**Comment by iancooper** [comment]
I need to carve out some time to think about this more deeply

**Comment by iancooper** [comment]
I don't think Brighter plays well with scoping to request-response because it may need to react beyond that i.e. to publisher confirms or callabacks. An Outbox does not really work, unless it is a singleton. Our memento pattern for a pipeline is explicitly a singleton. So we really ought to say: you should register Brighter as a singleton and any scoped dependency should be created by one of our factories and then deleted. 

And that to me implies that we need to say: all scoping requirements need to be handled by the factory that creates and destroys your instances, because we don't want to make Brighter a scoped dependency itself

**Comment by iancooper** [comment]
I also suspect that we would benefit from a clear rule when reasoning about Brighter: it's most likely been instantiated as a singleton and so must be thread safe.

**Comment by iancooper** [comment]
BTW this was not always as true, but the move to support Outbox and callbacks has made it very true.

**Comment by iancooper** [comment]
There are a range of PRs dealing with making us behave nice with an EF Scope

**Comment by preardon** [comment]
@iancooper I think this Issue will go away with the work you've done around splitting the Command processor as its not the Transaction shared Connection Provider wont be the one used for the Singleton outbox.

One thing I would like to talk about next time we're on a call is how we feel about this, as the way I've got it running locally is that I use a SQLAuth Connection Provider and a EF Connection provider of the transaction connection provider.  I don't generally like things where you could technically get into a state where you expect 2 thing to look in the same place but could configure it to use a different DB, but I suppose this isn't the biggest issue if you configure things correctly.

**Comment by iancooper** [comment]
@preardon OK, let's discuss that next time before we try to kill this one
