### ISSUE TITLE
Unable to cast object of type 'namespace.RequestHandlerAsync' to type 'Paramore.Brighter.IHandleRequests

### ISSUE THREAD

**Issue by devreepiet** [BrighterCommand/Brighter#2131]
### Describe the bug
I was experimenting with the framework, until I came across a problem with RabbitMQ and an AsyncHandler.
When I send a Command from my API (No issues there), a Console app receives the Command via RabbitMQ. but when it is trying to handle the Request the application crashes. When I change the Handler from Async to a Sync handler it does however work. 
I don't know if I am doing something wrong or if fit is even possible?

### To Reproduce
Given that the API side works I am going to only include the Console Application Config.

The handler that is not working. Note I included the Not Async handler below the handler that is throwing the Exceptions.
![image](https://user-images.githubusercontent.com/78440527/170837196-18d28b08-421d-45a8-bb41-c1e12d553227.png)

The Config of the Library.
![image](https://user-images.githubusercontent.com/78440527/170837237-4d68ad66-5905-4911-9b55-b2a338e8175e.png)

### Exceptions (if any)
![image](https://user-images.githubusercontent.com/78440527/170837324-e5c2fec4-4e9c-4d9a-b02a-dab9b08e1227.png)

### Further technical details
- Brighter version 9.1.2
- Net 6.0

**Comment by DevJonny** [comment]
Hi @devreepiet. From the error you've shared it looks like when the message was consumed from RMQ it was send down the synchronous path, instead of the asynchronous path. It's not immediately obvious what is wrong, but I suspect it's something in the setup of Brighter.

Are you able to share the whole solution with us?

**Comment by devreepiet** [comment]
Hello @DevJonny. I that case I am very sorry, I think everything that I used in my original project is in here.
https://github.com/devreepiet/BrighterTest

**Comment by DevJonny** [comment]
Not at all @devreepiet we're here to help, and I may be wrong and it's a bug! Thank you for sharing the code, I'll check it out and see what I can find 👍

**Comment by devreepiet** [comment]
> Not at all @devreepiet we're here to help, and I may be wrong and it's a bug! Thank you for sharing the code, I'll check it out and see what I can find 👍

Any news? It seems to me that this is either an important issue or that I actually have configured it wrong. 

PS: no pressure, just making sure this is not landing on the forgotten pile.

**Comment by DevJonny** [comment]
@devreepiet sorry I hadn't gotten back to you sooner, I had been looking at but hadn't gotten very far. However I now realise why, I was looking at it from the a `.Send(..)` point of view rather than the `.Post(..)` side. Doh! 

Glad you managed to resolve it yourself. If you want to raise a pull request that makes the XML comment arounds this more obvious the please do, if not I will try and grab some time to make it more obvious.
