### ISSUE TITLE
Confirm that we can run under .NET Core 2.0

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#226]
This is a todo list for anything that comes up from tracking the .NET Core 2.0 releases.
We probably need to do this on a branch, and regularly merge from master
https://blogs.msdn.microsoft.com/dotnet/2017/05/10/announcing-net-core-2-0-preview-1/

**Comment by has-taiar** [comment]
Hi @iancooper, 
I am starting on a new project and I am glad that I found Brighter, I am hoping to use Brighter with Asp.Net Core :(
I am happy to offer any help to get this to .NET Core, so that we can use it and the rest of the community can use it too :)

The first blocker I saw was that it relies on Azure Service Bus Nuget packages which is compiled for the full .Net Framework. There is a new .netStandard-compatiblible version of the ASB nuget here: https://github.com/Azure/azure-service-bus-dotnet

Is there any other dependency on the full .net framework?

**Comment by iancooper** [comment]
We have been running against .NET 2.0 projects now, so closing this issue (see FutureStack)
