### ISSUE TITLE
[ASK] Can you share a classic hexagonal sample with ASP.NET Core and Brighter ?

### ISSUE THREAD

**Issue by HamedFathi** [BrighterCommand/Brighter#237]
in Readme you said 

> When implementing a hexagonal architecture, one question is how to implement a port.

so I want to know can you share a simple classic hexagonal sample with ASP.NET Core, Brighter, EF Core, Logging Framework, IoC, ... in your Github? it can be very useful for somebody like me.

**Comment by iancooper** [comment]
We built one here: https://github.com/Arc-Lightning/FutureStack

I am tempted to move that repo into BrighterCommand as it is a pretty good example, ad we don't have anything else in that org.

Would that help?

**Comment by iancooper** [comment]
Actually @dstockhammer's version is better: https://github.com/dstockhammer/todo-backend-aspnetcore

**Comment by HamedFathi** [comment]
@iancooper 

Are both of them based on Hexagonal Architecture ?

because I can find any sample based on Onion or Clean Architecture based on ASP.NET Core but this is first time for Hexagonal :)

**Comment by iancooper** [comment]
Yes. If you look at ToDoCore you can see that we divide up the assembly into Adapters, Ports, and Model (Domain). The Ports surround the Domain, and both Tests and Primary Adapters (such as ToDoAPI and ToDoApp) call into the Domain through these Ports. Core includes Adapters because these are secondary, ones that we call from within the Ports, such as a Repository pattern.

**Comment by iancooper** [comment]
I'll move FutureStack into BrighterCommand.

Let me know if that helps to resolve the issue.

**Comment by iancooper** [comment]
Now at: https://github.com/BrighterCommand/FutureStack
