### ISSUE TITLE
Authorization?

### ISSUE THREAD

**Issue by BringerOD** [BrighterCommand/Brighter#245]
I am thinking about using Brighter!   (Sorry for the rambling post.)

Can anyone give me some guidance on how you are handling authorization?  Do you add an attribute and handle it in the pipeline?  

Currently I have a simple command bus, which I wrote,  that checks for a custom authorization attribute,  checks for security and either throws an exception or allows the command to proceed. and adds the users information to the command via the handler method.

With Brighter and other libraries like NServicebus,  you can potentially have another machine handle the command or request via the task queue.  This makes me think I should handle authorization before I run the command at all.  Problem is,  there are multiple presentation layers that can run a command,  which would violate DRY.  Also,  how would I then get the users information in the command handler.  I use the user information to add authorized by information to the command and eventual event data.

I would prefer to decorate the command, because that is what I want secured,  but again,  if the command is sent to a queue and another process picks it up,  the actor is lost,

I guess I could add the authorizing entity,  could be a person or a service,  to the command data,  but that feels like I am adding a cross cutting concern's data to all commands.

Does anyone else have this architectural problem?  How did you solve it?

Maybe create a custom authorization attribute that checks authorization and then adds the authorized entity to the context bag?  If I need to implement a task queue create a mapper that transfer authorized entity as well?

Bryan

**Comment by dstockhammer** [comment]
I would agree with your first proposed solution and handle authZ before sending the command. The benefit of doing this is that you can give feedback about authZ failure earlier / synchronously. This means you don't have to implement some async process to feed back the information about failures. Subsequently, you don't need to worry about authZ in the handler at all, which again saves you some branching. Plus, as a minor benefit, you don't incur the the additional overhead of the message on the queue.

Now the problem with this approach is that authZ is clearly domain/business logic and doesn't belong in a presentation layer. So you can't do it there before sending the command.
To solve that, I would have another synchronous port/handler to deal with authZ and possible all other required validations you can do immediately.

So in your presentation layer you would `Send` the command to an in process handler. There you validate, and on success you `Post` the command to put it on a queue for async processing. For this solution you can either use the same command (as in, C# class), or two distinct commands to be a bit more explicit.

**Comment by BringerOD** [comment]
Thanks for the quick reply!  

So in my scenario,  I am using event sourcing for portions of my system, which basically stores what happens in event form over time, and I need to store who or what authorized the command that produced the event.  

Do I attach the authorized entity to the command object?  For some reason I just don't want to do it.  LOL!

For now that does seem to be the best option though.

**Comment by dstockhammer** [comment]
Maybe I'm not completely following your scenario, but I don't see why event sourcing requires you to perform authZ at the time of handling the command? You can still attach the entity if that's your requirement. But wouldn't an ID and version be sufficient?

**Comment by BringerOD** [comment]
Sure,  of course,  event sourcing does not require it.  We are just adding it almost as meta data with each event.  Most if not all events in our system are secured,  so we want to be able to see who or what was the authorizing entity.

The object is small it does have a place for a userid if it was a user request, but the request can come from another service that is not a user and does not have a user id.  

Anyway,  adding it to the command does seem to be the way to go.  I like the idea of a process handler.  Mentally I was thinking Brighter would be that,  but I see no reason you cant have both. 

Thanks for the suggestion.   Sometimes the simple answer is the best answer.

**Comment by iancooper** [comment]
OK I assume that the scenario is that the authorization is part of the domain i.e. User ins n Role X and Role X has permission to do Y, 

In Process Handler
----------------------
For an in-process handler we tend to solve this problem by passing the actor downstream on the command, and then determining if the actor is authorized as part of the handler for that command. We use an exception to return from the handler in this event, and catch that in the caller i.e. the actor could not perform this event. Note that we can use this for 'async' provided the presentation layer does not return to the user until the 'async' completes, i.e. Web API, If the request returns first, treat as out-of-process, which is the way we would handle it anyway.

Out of Process Handler
-----------------------
In a sense this is the same, pass the actor on the command and check that they can perform the operation before committing it, but... there is no one to respond to when you determine that the operation cannot be performed, and discarding the message means the only way you will find out it failed is by checking the logs.

So usually I would first handle the message in-process using a handler, who sole job was to check permissions, and then if those passed, post the message onto a queue so that the out of process handler could pick it up and execute. There is a risk that the actor loses permissions before they can act in the async handler, but that is a more manageable set of messages to log and ack as a 'timing failure'. But here we get into business logic. It might be acceptable to check sychronously and not re-check on the out-of-process worker, because you accept that when this kind of race condition occurs, you take the permissions at the point they were checked not the point the change they protected was applied. or you might decide that you can't accept this and that where an out-of-process message fails due to permission checks since the in-process handler dispatchted it, you just ack and log.

Hope that helps,

Ian

**Comment by iancooper** [comment]
I'm going to close the issue, as there have been no further comments
