### ISSUE TITLE
[Bug] Option to Not Round Off Timestamp to Seconds

### ISSUE THREAD

**Issue by siewchinglim** [BrighterCommand/Brighter#2630]
I would like to get the original timestamp from Kafka message. However, currently Brighter will automatically round off the timestamp to seconds while receiving the message from Kafka. Is it possible to provide an option to get the original timestamp?

![image](https://user-images.githubusercontent.com/23093177/232980195-88b47f09-4761-4495-b349-8180e93f938d.png)

**Comment by iancooper** [comment]
This will be fixed by #2560; it was included in that work because we were addressing a number of issues tehre

**Comment by iancooper** [comment]
It is worth noting that timestamp accuracy will be a little out in this version on some outboxes due to milliseconds precision of some databases. We will introduce Db version management for Outboxes, and once we have that we will look at upgrading some of our Outboxes to use better precision datatime types or record ticks as well as dates.

**Comment by SteveBush** [comment]
See #2944 for how the internal representation of a TimeStamp was changed for Sqlite.
