### ISSUE TITLE
[Feature] Support setting a service URL when configuring an `AWSMessagingGatewayConnection`

### ISSUE THREAD

**Issue by dhickie** [BrighterCommand/Brighter#3109]
**Is your feature request related to a problem? Please describe.**
When working with SNS, we do local testing using LocalStack. This involves starting a LocalStack container and pointing AWS services in code to the container rather than to a real AWS environment.

When using SNS as an external bus, there's no option to provide a service URL, and so it defaults to a real AWS environment, making testing using LocalStack impossible.

**Describe the solution you'd like**
When creating an `AWSMessagingGatewayConnection` instance, support optionally supplying a `ServiceURL` value.

**Comment by iancooper** [comment]
@dhickie Let's pick this up. Let me know if you want to have a stab at it, or for me to pick it up instead.

**Comment by dhickie** [comment]
@iancooper Happy to take a look at this one. Is one of `release/9x` or `release/9X` the branch I should look at for forking?

**Comment by iancooper** [comment]
> @iancooper Happy to take a look at this one. Is one of `release/9x` or `release/9X` the branch I should look at for forking?

Our process is a little borked here TBH. Usually I do the following:

- Fork master and fix in V10; raise a PR, get a review
- Once merged into V10 fork release/9X and raise a PR there (https://github.blog/2016-08-15-change-the-base-branch-of-a-pull-request/) that is the tricky bit because you need to avoid a PR against master (ask me how I know)

You can do it the other way around if that makes more sense.
