### ISSUE TITLE
Bug: DynamoDbOutbox Archiver Missing Topics

### ISSUE THREAD

**Issue by jtsalva** [BrighterCommand/Brighter#3351]
### Describe the bug
Current implementation depends on `DynamoDbOutbox._topicName` being populated [as messages are added to the outbox](https://github.com/BrighterCommand/Brighter/blob/d7ffd74204a49cec068a58c3746fd03800ae67dc/src/Paramore.Brighter.Outbox.DynamoDB/DynamoDbOutbox.cs#L120). The archiver is trying to find messages through the async outbox but the sync version is used when adding to the outbox.

```
services
    .AddBrighter()
    .UseExternalBus(...)
    .AutoFromAssemblies()
    .UseDynamoDbOutbox() <---- registers 3 instances of the outbox, IAmAnOutbox, IAmAnOutboxSync, IAmAnOutboxAsync
    .UseOutboxSweeper() <---- uses non-async outbox
    .UseOutboxArchiver(new NullOutboxArchiveProvider()); <---- uses async outbox
```

### Proposed fix
**Short term**
Make `DynamoDbOutbox._topicNames` static

**Long term**
Maybe it should be possible to derive topic names from publications so that the archival process can run without needing any messages added first

### Further technical details
- Brighter v9

**Comment by dhickie** [comment]
I can't see a good reason for having three instances of the outbox registered, so to me the most sensible option would be to ensure only a single instance of the dynamo outbox is registered for all three interfaces.

One possible issue there is that if you create a `DynamoDbOutbox` instance inside `UseDynamoDbOutbox` and add that instance directly, then the method can't be called until `IAmazonDynamoDB` has been registered, instead of just relying that it's going to be registered at _some_ point. So perhaps, then, `BuildDynamoDbOutbox` should, instead of automatically creating a new outbox instance, try to retrieve the implementation of `IAmAnOutbox` and then return that instance if it exists. Otherwise return a new instance.

**Comment by iancooper** [comment]
>Maybe it should be possible to derive topic names from publications so that the archival process can run without needing any messages added first

In V10 we have the Topic on the Publication, we could backport this to V9, as it is additive and not a breaking change.

**Comment by iancooper** [comment]
>I can't see a good reason for having three instances of the outbox registered, so to me the most sensible option would be to ensure only a single instance of the dynamo outbox is registered for all three interfaces.
Agreed, that is an error. It implements all three for us. This is really a lot about some storage providers not having all these capabilities. In a few cases that is historical. It is possible that we could review and remove the sync storage provider support in V10 as no longer needed. @preardon Thoughts?

**Comment by jtsalva** [comment]
@dhickie @iancooper I've raised #3358 as suggested

**Comment by iancooper** [comment]
@jtsalva Approved and merged. Do we need to fix this in V9 as well?

**Comment by jtsalva** [comment]
@iancooper the merged PR was for v9. I had a look at the v10 master branch and I can't find `UseDynamoDbOutbox` there
