### ISSUE TITLE
Get an example running with Azure Service Fabric

### ISSUE THREAD

**Issue by iancooper** [BrighterCommand/Brighter#76]
It should be possible to use Azure Service Fabric for hosting services instead of TopShelf Windows Services and IIS hosted APIs. I'm going to do a proof of concept, for part of an upcoming Microservices talk.

**Comment by iancooper** [comment]
@dstockhammer now has his

**Comment by loneshark99** [comment]
Is this done yet?

**Comment by dstockhammer** [comment]
No, not really. I've been playing around with Azure Functions and I think that environment is superior to Service Fabric for our needs. However there's a lot of churn with VS Function tools at the moment so that I've decided to wait until a VS 2017 version is available. See https://github.com/Azure/Azure-Functions/issues/201

**Comment by loneshark99** [comment]
ok
